#! /bin/bash

rm -f core.*

RDIR=~/releases
NAME=librcc


if [ ! -d $RDIR ]; then
    if [ -a $RDIR ]; then
	echo "Release directory isn't a directory!"
	exit
    fi
    mkdir -p $RDIR
fi

version=`cat VERSION | perl -e "while (<STDIN>) {  if (m/(\d+\.\d+(.\d+)?)/) { print \\$1; } }"`
cvs=`cat VERSION | perl -e "while (<STDIN>) {  if (m/\d+\.\d+(.\d+)?.*(cvs|CVS|Cvs)/) { print 'cvs'; } }"`
if [ "$cvs" == "cvs" ]; then
    rname="$NAME-`date +%y%m%d.%H`"
else
    rname="$NAME-$version";
fi
if [ -d $RDIR/$rname ]; then
    rm -rf $RDIR/$rname
fi
mkdir -p $RDIR/$rname
if [ ! -d $RDIR/$rname ]; then
    echo "Can't create directory!!!"
    exit
fi
cp -a * $RDIR/$rname
#cp -al * $RDIR/$rname

(
    cd $RDIR/$rname
    ./autogen.sh
    ./configure
    make clean distclean distclean-am -C examples 
    make clean distclean distclean-am
    find . -name CMakeFiles -print0 | xargs -0 rm -rf
    find . -name CMakeCache.txt -print0 | xargs -0 rm -rf
    find . -name cmake_install.cmake -print0 | xargs -0 rm -rf
    find . -name "*~" -print0 | xargs -0 rm -rf

    rm -rf autom4te*.cache
    rm -rf "{arch}"
    rm -rf `find . -name .arch-ids`
#    rm -rf `find . -name .deps`
#    rm -f config.log config.status
    rm -rf debian
    cd ..
    if [ -a $rname.tar.bz2 ]; then
	rm -f $rname.tar.bz2
    fi
    tar cjf $rname.tar.bz2 $rname
    rm -rf $rname

    if [ ! "$cvs" == "cvs" ]; then
	scp $rname.tar.bz2 csa@dside.dyndns.org:/home/csa/public_html/files/rusxmms/
	ssh csa@dside.dyndns.org ln -sf $rname.tar.bz2 /home/csa/public_html/files/rusxmms/$NAME-latest.tar.bz2
    fi
)
